[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
txhookmagick = "5j8BynmEHtTtC3SqkzTG87vVCxjyoscmW3fPh18f3isg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
